### ISSUE TITLE
Unable to scan the QR code generated in terminal due to dark background color.

### ISSUE THREAD

**Issue by rajeev29five** [sayanarijit/qrcode.show#22]
**Describe the bug**

Unable to read QR code generated in terminal because of dark background color of terminal. But works fine when background color is changed to white.

**To Reproduce**
1. Open Git bash with default background (BLACK) and foreground (GREY) color. 
2. curl qrcode.show/test.
3. QR code will be generated.
4. Try to read the QR code. 
5. Scanner is unable to read the code.
6. Now change the background color to WHITE and foreground to BLACK.
7. Follow step 2, 3 and 4.
8. Scanner is able to read the code.

**Expected behavior**
QR code scanner should be able to read the code. 

**Screenshots**
![qrcodeissue](https://user-images.githubusercontent.com/16323302/140645328-049893cc-a6d3-45fd-9550-c3bb9cc7d649.png)

**Desktop (please complete the following information):**
 - OS : Windows
 - Browser :  N/A. Using terminal(Git Bash) to generate code.
 - Version : N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser  N/A
 - Version  N/A

**Additional context**
N/A

**Comment by sayanarijit** [comment]
Hi. Inverting the colors would create problems for terminals with white background. One easy hack is to select the QR code using mouse. That should invert the colors.

**Comment by rajeev29five** [comment]
Thanks! that hack worked.
