### ISSUE TITLE
Document in Markdown

### ISSUE THREAD

**Issue by Siddhant-K-code** [sayanarijit/qrcode.show#4]
We Can Make this project, `README` in markdown with code snippets, headers, images, & more.

**Comment by sayanarijit** [comment]
Hi... I like the simplicity of plain text, specially when it comes to command-line tools. But if you'd like, you can raise a PR. Let's have both :)

**Comment by Siddhant-K-code** [comment]
Yeah Sure!


I was saying that, it looks good on GitHub Repo. ( better readability )

**Comment by Siddhant-K-code** [comment]
@sayanarijit Please Review & Merge.

**Comment by sayanarijit** [comment]
Looks nice... Thank you :+1:

**Comment by sayanarijit** [comment]
I'll make some minor fixes.

**Comment by sayanarijit** [comment]
Ref: https://github.com/sayanarijit/qrcode.show/pull/16
