### ISSUE TITLE
CORS Missing Allow Origin

### ISSUE THREAD

**Issue by danielkellyio** [sayanarijit/qrcode.show#7]
Anyway you could allow any origin so that QR code could be generated client side in the browser?
```Access-Control-Allow-Origin: *```

I'm getting failed network requests when trying to do this in the browser. See example here: https://codesandbox.io/s/qrcode-test-gqktd?file=/src/App.vue

Thanks!

**Comment by sayanarijit** [comment]
Hi, I can allow such overly permissive headers for now, however, please do not use it in mission critical applications. I have a limited budget and might have to put restrictions on the usage to avoid abuse in the future.

**Comment by danielkellyio** [comment]
Thanks!
